config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'homes#top'

  get '/locale', to: 'languages#locale', as: 'locale'

  resources :dogs do
    collection do
      get 'search'
      get 'search_results'
      get 'matching_results'
    end
  end

  resources :user_choices

  resources :user_steps do
    collection do
      get 'first'
      get 'second'
      get 'third'
      get 'fourth'
      get 'fifth'
      get 'sixth'
      get 'matching_results'
    end
  end

  resources :users, only: [:show]

  resources :favorites, only: [:create, :destroy]

  resources :posts
end

app/controllers/user_steps_controller.rb
class UserStepsController < ApplicationController
  # before_action :set_user_step, only: %i[ show edit update destroy ]

  def first
    @user_choice = UserChoice.new
  end

  def second
    # if session[:vehicle] || params[:user_choice][:vehicle]
    @user_choice = UserChoice.new
    if params[:user_choice]
      session[:vehicle] = user_choice_params[:vehicle]
      
    else
      # redirect_to first_user_steps_path unless session[:vehicle]
      # redirect_to second_user_steps_path
      render action: :first
    end
  end

  def third
    if params[:user_choice]
      session[:cleaning] = user_choice_params[:cleaning]
      @user_choice = UserChoice.new
    else
      @user_choice = UserChoice.new
      render action: :second
    end
  end

  def fourth
    if params[:user_choice]
      session[:active] = user_choice_params[:active]
      @user_choice= UserChoice.new
    else
      @user_choice = UserChoice.new
      render action: :third
    end
  end

  def fifth
    if params[:user_choice]
      session[:exercise] = user_choice_params[:exercise]
      @user_choice = UserChoice.new
    else
      @user_choice = UserChoice.new
      render action: :fourth
    end
  end

  def sixth
    if params[:user_choice]
      session[:home] = user_choice_params[:home]
      @user_choice = UserChoice.new
    else
      @user_choice = UserChoice.new
      render action: :fifth
    end
  end

  def create
    unless params[:user_choice]
      @user_choice = UserChoice.new
      return render :sixth 
    end
    @user_choice = current_user.build_user_choice(
      vehicle: session[:vehicle],
      cleaning: session[:cleaning],
      active: session[:active],
      exercise: session[:exercise],
      home: session[:home], 
      house: user_choice_params[:house]
    )
    if @user_choice.save
      session[:id] = @user_choice.user_id
      redirect_to  matching_results_dogs_path
    else
      render 'new'
    end

  end

  private

  # def set_user_step
  #   @user_step = UserStep.find(params[:id])
  # end

  def user_choice_params
    params.require(:user_choice).permit(:vehicle, :cleaning, :active, :exercise, :home, :house, :user_id)
  end
end

app/helpers/user_steps_helper.rb
module UserStepsHelper
end

app/views/user_steps/fifth.html.erb
<%= form_with model: @user_choice, url: sixth_user_steps_path, method: :get do |form| %>
  <h6 class="which_one">当てはまる方を選んでください</h6>
  <p class="enum-choice"><%=t('.About family')%></p>

  <div class="enum-choice">
    <%= form.radio_button :home, :kids, class: "radio-inline__input" %>
    <%= form.label(:home, "kids", value: "kids", class: "radio-inline__label") %>
    <%= form.radio_button :home, :none, class: "radio-inline__input" %>
    <%= form.label(:home, "none", value: "none", class: "radio-inline__label") %>
  </div>
  
  <div class="actions">
    <%= form.submit "次へ", class: "button004"%>
  </div>
  <div class="step_back">
   <%= link_to 'Back', fourth_user_steps_path %>
  </div>

  <div class="tip">
    <p>わんちゃんとこどもが遊んでいると可愛らしいですね。</p>
    <p>わんちゃんとお子さんが仲良く遊べたら素敵です。</p>
    <p>しかし、犬種や性格によっては子どもが苦手なわんちゃんもいます。</p>
    <p>子どもと相性の良い犬種、思いつく犬種はありますか？</p>
  <div>
<% end %>

app/views/user_steps/first.html.erb
<%= form_with model: @user_choice, url: second_user_steps_path, method: :get do |form| %>
  <h6 class="which_one">当てはまる方を選んでください</h6>
  <p class="enum-choice"><%= t('.What do you ride?')%></p>

  <div class="enum-choice">
    <%= form.radio_button(:vehicle, :car, class: "radio-inline__input" )%>
    <%= form.label(:vehicle, t('.car'), value: "car", class: "radio-inline__label") %>
    <%= form.radio_button(:vehicle, :train, class: "radio-inline__input" )%>
    <%= form.label(:vehicle, t('.train'), value: "train", class: "radio-inline__label") %>
  </div>


  <div class="actions">
    <%= form.submit "次へ", class: "button004" %>
  </div>

  <div class="step_back">
    <%= link_to t('.Back'), user_path(current_user) %>
  </div>

  <div class="tip">
    <p>わんちゃんとお出かけしたいところはありますか？</p>
    <p>電車や新幹線でも一緒にお出かけができます。</p>
    <p>キャリーの規定サイズやルールは会社により異なります。</p>
    <p>お出かけしたい場所と一緒に調べてみてはいかがですか？</p>
  </div>
  
<% end %>

app/views/user_steps/fourth.html.erb
 <%= form_with model: @user_choice, url: fifth_user_steps_path, method: :get do |form| %>
  <h6 class="which_one">当てはまる方を選んでください</h6>
  <p class="enum-choice"><%= t('.Exercise') %></p>

  <div class="enum-choice">
    <%= form.radio_button :exercise, :like, class: "radio-inline__input" %>
    <%= form.label(:exercise, "like", value: "like", class: "radio-inline__label") %>
    <%= form.radio_button :exercise, :dislike, class: "radio-inline__input" %>
    <%= form.label(:exercise, "dislike", value: "dislike", class: "radio-inline__label") %>
  </div>
  
  <div class="actions">
    <%= form.submit "次へ", class: "button004" %>
  </div>
  <div class="step_back">
    <%= link_to 'Back', third_user_steps_path %>
  </div>

  <div class="tip">
    <p></p>
    <p></p>
    <p></p>
    <p></p>
  </div>
  
<% end %>

app/views/user_steps/second.html.erb
 <%= form_with model: @user_choice, url: third_user_steps_path, method: :get do |form| %>
  <h6 class="which_one">当てはまる方を選んでください</h6>
  <p class="enum-choice"><%= t('.Do you like cleaning up?') %></p>
  
  <div class="enum-choice">
    <%= form.radio_button :cleaning, :like, class: "radio-inline__input"%>
    <%= form.label(:cleaning, "like", value: "like", class: "radio-inline__label") %>
    <%= form.radio_button :cleaning, :dislike, class: "radio-inline__input" %>
    <%= form.label(:cleaning, "dislike", value: "dislike", class: "radio-inline__label") %>
  </div>
  
  <div class="actions">
    <%= form.submit "次へ", class: "button004"%>
  </div>
  <div class="step_back">
    <%= link_to 'Back', first_user_steps_path %>
  </div>

  <div class="tip">
    <p>さまざまな毛色のわんちゃんがたくさん。</p>
    <p>毛が抜けやすい犬種や、毛が抜けにくい犬種がいます。</p>
    <p>部屋中毛だらけなんてことも。</p>
    <p>日頃のお掃除や、犬アレルギーについても考えてみましょう。</p>
  <div>
<% end %>

app/views/user_steps/sixth.html.erb
 <%= form_with model: @user_choice, url: user_steps_path, method: :post do |form| %>
  <h6 class="which_one">当てはまる方を選んでください</h6>
  <p class="enum-choice"><%= t('.About house')%></p>

  <div class="enum-choice">
    <%= form.radio_button :house, :owned, class: "radio-inline__input" %>
    <%= form.label(:house, "owned", value: "owned", class: "radio-inline__label") %>
    <%= form.radio_button :house, :lent, class: "radio-inline__input" %>
    <%= form.label(:house, "lent", value: "lent", class: "radio-inline__label") %>
  </div>
  
  <div class="actions">
    <%= form.submit "次へ", class: "button004"%>
  </div>
  <div class="step_back">
    <%= link_to '戻る', fifth_user_steps_path %>
  </div>

  <div class="tip">
    <p>お家に帰ったら、わんちゃんが待っている暮らし、素敵ですよね。</p>
    <p>賃貸で、ペット可の物件が少なかったり、</p>
    <p>小型犬のみとサイズが指定されていることが多いです。</p>
    <p>飼いたい犬種の成犬時のサイズの確認は大切ですね。</p>
  <div>
<% end %>

app/views/user_steps/third.html.erb
 <%= form_with model: @user_choice, url: fourth_user_steps_path, method: :get do |form| %>
  <h6 class="which_one">当てはまる方を選んでください</h6>
  <p class="enum-choice"><%= t('.Active day off')%></p>
  
  <div class="enum-choice">
    <%= form.radio_button :active, :like, class: "radio-inline__input" %>
    <%= form.label(:active, "like", value: "like", class: "radio-inline__label") %>
    <%= form.radio_button :active, :dislike, class: "radio-inline__input" %>
    <%= form.label(:active, "dislike", value: "dislike", class: "radio-inline__label") %>
  </div>
  
  <div class="actions">
    <%= form.submit "次へ", class: "button004" %>
  </div>


  <div class="step_back">
    <%= link_to 'Back', second_user_steps_path %>
  </div>

  <div class="tip">
    <p>牧羊犬をご存知ですか？</p>
    <p>放牧されている羊をまとめ牧舎に連れ戻したり、迷ったヒツジを群れに連れ戻すことを行い、</p>
    <p>体力があり、頭を使うのが得意です。</p>
    <p>他にも牧畜犬や猟犬などもいます。</p>
    <p>ドッグスポーツで活躍している子がたくさんいるので、
ドッグスポーツについて調べてはいかがでしょうか。</p>
  </div>

<% end %>