config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'homes#top'

  get '/locale', to: 'languages#locale', as: 'locale'

  resources :dogs do
    collection do
      get 'search'
      get 'search_results'
      get 'matching_results'
    end
  end

  resources :user_choices

  resources :user_steps do
    collection do
      get 'first'
      get 'second'
      get 'third'
      get 'fourth'
      get 'fifth'
      get 'sixth'
      get 'matching_results'
    end
  end

  resources :users, only: [:show]

  resources :favorites, only: [:create, :destroy]

  resources :posts
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_many :favorites
  has_many :posts

  validates :name, presence: true
  validates :image_url, presence: true

  #enum color
  enum size: { big: 0, medium: 1, small: 2 }, _prefix: true
  enum vehicle: { car: 0, train: 1 }, _prefix: true
  enum cleaning: { like: 0, dislike: 1 }, _prefix: true
  enum active: { like: 0, dislike: 1 }, _prefix: true
  enum exercise: { like: 0, dislike: 1 }, _prefix: true
  enum home: { kids: 0, none: 1 }, _prefix: true
  enum house: { owned: 0, lent: 1 }, _prefix: true
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_q, only: [:search, :search_results]

  def index
    @dogs = Dog.page(params[:page])
  end

  def new
    @dog = Dog.new
  end

  def create
    Dog.create(dog_params)
    redirect_to dogs_url
  end

  def show
    @dog = Dog.find(params[:id])
    @user_favorite = current_user.favorites.find_by(dog_id: @dog.id)
  end

  def search
  end
  
  def search_results
    @results = @q.result.page(params[:page])
  end
  
  def matching_results
    @dogs = Dog.page(params[:page]).per(10)
  end
  private
 

  
  def set_q
    @q = Dog.ransack(params[:q])
  end

  def dog_params
    params.require(:dog).permit(:name, :size, :vehicle, :cleaning, :active, :exercise, :home, :house, :image_url)
  end

end

app/helpers/dogs_helper.rb
module DogsHelper
   def matching_result(dog)
    @user_choices = current_user.user_choice
    user_choices = [ @user_choices.vehicle, @user_choices.cleaning, @user_choices.active, @user_choices.exercise, @user_choices.home, @user_choices.house ]
    dog_choices = [ dog.vehicle, dog.cleaning, dog.active, dog.exercise, dog.home, dog.house ]
    matching_count = 0
    user_choices.each_with_index do |user_choice, i|
      matching_count += 1 if user_choice == dog_choices[i]
    end
    @matching = (matching_count * 100/6).round(-1)
  end
end

app/views/dogs/index.html.erb
<h1><%=t('.Dogs')%></h1>
<div class="center-text">
  <table>
    <tbody>
      <div class="card-deck">
        <% @dogs.each do |dog| %>
          <div class="card" flex-direction:row>
            <div class="card-header">
              <%= dog.name %>
            </div>
            <div class="card-body">
              <%= image_tag dog.image_url, size: '300x250'%>
              <%= link_to t('.Show'), dog %>
            </div>
          </div>
        <% end %>
      </div>
    </tbody>
  </table>

  <br>

  <%= link_to t('.Search Dogs'), search_dogs_path %>

  <%= paginate @dogs %>

  <%= link_to t('.My page'), user_path(current_user.id)  %>

app/views/dogs/matching_results.html.erb
<div class="center-text">
  <%= link_to t('.Search Dogs'), search_dogs_path %>

  <h1><%=t('.Matching results')%></h1>
  <table>
    <thead>
      <tr>
        <th><%=t('.Name')%></th>
        <th><%=t('.Matching')%></th>
        <th><%=t('.Image')%></th>
      </tr>
    </thead>  <tbody>
      <% Dog.all.each do | dog | %>
        <tr>
          <td><%= dog.name %></td>
          <td class="heart"><p class="rate"><%= matching_result(dog)%>%</p></td>
          <td><%= image_tag dog.image_url, size: '600x500'%></td>
          <td><%= link_to t('.Show'), dog %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= paginate @dogs %>

app/views/dogs/search.html.erb
<h1><%=t('.Let find doggos')%></h1>
<div class="row justify-content-center">
  <%= search_form_for @q, url: search_results_dogs_path do |f| %>
    <div class="searching">
      <%= f.label :name_cont, t('.Breed') %>
      <%= f.search_field :name_cont, placeholder: "poodle" %>
    </div>
    <div class="searching">
      <%= f.label :size, t('.Size') %>
      <%= f.select :size_eq, Dog.sizes_i18n.invert, { include_blank: "指定なし" } %>
    </div>
    <div class="searching">
      <%= f.check_box :cleaning_eq, {}, 1 , nil%>
      <%= t('.Low-shedding') %>
      <%= f.check_box :home_eq, {}, 0 , nil%>
      <%= t('.Gentle') %>
      <%= f.check_box :active_eq, {}, 0 , nil%>
      <%= t('.Dog sport') %>
      <%= f.check_box :exercise_eq, {}, 1 , nil%>
      <%= t('.Short walking') %>
      <%= f.check_box :house_eq, {}, 1 , nil%>
      <%= t('.Lent house') %>
    </div>
    <div class="button text-center">
      <%= f.submit t('.Search')  %>
    </div>
  <% end %>
</div>

<%= link_to t('.Index'), dogs_path %>

app/views/dogs/search_results.html.erb
<h1><%=t('.Search results')%></h1>
  <div class="card-deck">
    <% @results.each do |dog| %>
      <div class="card" flex-direction:row>
        <div class="card-header">
          <h4><%= dog.name %></h4>
        </div>
        <div class="card-body">
          <%= image_tag dog.image_url, size: '300x250' %>
          <h3><%= link_to t('.Show'), dog %></h3>
        </div>
      </div>
    <% end %>
  </div>


<%= link_to t('.Search Dogs'), search_dogs_path %>
<%= link_to t('.Index'), dogs_path %>

<%= paginate @results %>

app/views/dogs/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= image_tag @dog.image_url, size: '500x400'%>
    </div>
    <div class="col-6">
      <div class="col-3"><strong><%= t('.Name')%></strong><br>
        <%= @dog.name %></div>
      <div class="col-3">
        <% if @user_favorite.present? %>
          <%= link_to '💜', favorite_path(id: @user_favorite.id), method: :delete %>
        <% else %>
          <%= link_to '💟', favorites_path(dog_id: @dog.id), method: :post %>
        <% end %></div>
      <div class="col-6"><strong><%= t('.Size')%></strong><br>
        <%= @dog.size_i18n %></div>
      <div class="col-6"><strong><%= t('.Feature')%></strong><br>
        <br><%= @dog.home_i18n %></div>
      <div class="col-6"><strong><%= t('.Cleaning') %></strong><br>
        <%= @dog.cleaning_i18n %></div>
      <div class="col-6"><strong><%= t('.Active')%></strong><br>
        <%= @dog.active_i18n %></div>
    </div>
  </div>
</div>



<%= link_to 'Back', dogs_path %>